# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_gamma <- function(a) {
    .Call(`_SynInt_random_gamma`, a)
}

maineffects_sampler <- function(R, X, Psi_inv, sigma_sq) {
    .Call(`_SynInt_maineffects_sampler`, R, X, Psi_inv, sigma_sq)
}

pot_MALA <- function(R, X1, X2, param, tau1sq, tau2sq, S1, S2, sigma_sq) {
    .Call(`_SynInt_pot_MALA`, R, X1, X2, param, tau1sq, tau2sq, S1, S2, sigma_sq)
}

grad_MALA <- function(R, X1, X2, param, tau1sq, tau2sq, S1, S2, sigma_sq) {
    .Call(`_SynInt_grad_MALA`, R, X1, X2, param, tau1sq, tau2sq, S1, S2, sigma_sq)
}

sq_sampler <- function(R, X1, X2, tau1sq, tau2sq, S1, S2, sigma_sq, old_param, eps_MALA, c_HMC, L_HMC) {
    .Call(`_SynInt_sq_sampler`, R, X1, X2, tau1sq, tau2sq, S1, S2, sigma_sq, old_param, eps_MALA, c_HMC, L_HMC)
}

SIDsampler_draws_adaptive_optimized <- function(y, Z, ME_mat, IE_list, eps_MALA, c_HMC, L_HMC, MC, n, p, p_cov, SigmaME, SigmaME_inv, SigmaInt, SigmaInt_inv, ME_nspl, IE_nspl, var_cov, cutoff, map_k_to_uv, zero_ind, accept_low, accept_high, accept_scale) {
    .Call(`_SynInt_SIDsampler_draws_adaptive_optimized`, y, Z, ME_mat, IE_list, eps_MALA, c_HMC, L_HMC, MC, n, p, p_cov, SigmaME, SigmaME_inv, SigmaInt, SigmaInt_inv, ME_nspl, IE_nspl, var_cov, cutoff, map_k_to_uv, zero_ind, accept_low, accept_high, accept_scale)
}

